version: '3.4'

services:
  oilcaseapi:
    image: ${DOCKER_REGISTRY-}oilcaseapi
    build:
      context: .
      dockerfile: Dockerfile

    ports:
        - "8080:8080"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    expose:
      - "1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "VERY_strong!_passsword"
    ports:
      - "1433:1433"